"""
=============================================================
SCRIPT 4: Dataset Folder Structure Setup
=============================================================
Usage:
    python setup_structure.py /path/to/dataset/root

Creates the recommended folder layout for an egocentric
robotics video pipeline and prints a tree overview.

Folder layout:
    /dataset
      /raw_videos        ← original mp4/avi recordings (read-only source of truth)
      /previews          ← keyframe JPGs + thumbnail grids
      /segments          ← trimmed or split clips from raw videos
      /annotations       ← per-frame or per-segment label files (CSV / JSON)
      /descriptions      ← NLP captions / action descriptions for each clip
      /final_dataset     ← processed samples ready for model training
        /train
        /val
        /test
=============================================================
"""

import sys
from pathlib import Path


# ─── ANSI colours ──────────────────────────────────────────
CYAN  = "\033[96m"
GREEN = "\033[92m"
BOLD  = "\033[1m"
DIM   = "\033[2m"
RESET = "\033[0m"


# ─── Folder structure definition ───────────────────────────
# Each entry: (relative_path, description_string)
STRUCTURE = [
    ("raw_videos",            "Original mp4/avi recordings — treat as read-only"),
    ("previews",              "Keyframe JPGs + thumbnail grids (auto-generated)"),
    ("segments",              "Trimmed / activity-split clips from raw videos"),
    ("annotations",           "Per-frame or per-segment labels (CSV / JSON / JSONL)"),
    ("descriptions",          "NLP captions / action descriptions per clip"),
    ("final_dataset/train",   "Training split — processed, ready for model input"),
    ("final_dataset/val",     "Validation split"),
    ("final_dataset/test",    "Test / held-out evaluation split"),
]

# Placeholder README content for each top-level folder
README_CONTENTS = {
    "raw_videos": (
        "# raw_videos\n\n"
        "Place your original .mp4 / .avi recordings here.\n"
        "**Do not modify these files** — they are the source of truth.\n\n"
        "Sub-folder suggestion:\n"
        "  raw_videos/<task_name>/<session_id>/<recording>.mp4\n"
    ),
    "previews": (
        "# previews\n\n"
        "Auto-generated by `extract_keyframes.py`.\n"
        "One sub-folder per video, containing 5 evenly-spaced JPG keyframes.\n"
        "Also contains `thumbnail_grid.png` for quick visual inspection.\n"
    ),
    "segments": (
        "# segments\n\n"
        "Trimmed clips cut from raw_videos (activity boundaries).\n"
        "Naming convention: `<video_stem>_seg<NNN>_<start>-<end>.mp4`\n"
    ),
    "annotations": (
        "# annotations\n\n"
        "Label files in CSV or JSONL format.\n"
        "Suggested schema (JSONL):\n"
        "  {\"video\": \"...\", \"segment\": \"...\", \"action\": \"...\",\n"
        "   \"start_frame\": 0, \"end_frame\": 120, \"confidence\": 1.0}\n"
    ),
    "descriptions": (
        "# descriptions\n\n"
        "Natural-language captions for each clip.\n"
        "One .txt file per segment, or a single descriptions.jsonl:\n"
        "  {\"segment\": \"seg001\", \"caption\": \"Person picks up a cup from shelf.\"}\n"
    ),
    "final_dataset": (
        "# final_dataset\n\n"
        "Processed, model-ready samples split into train / val / test.\n"
        "Each split mirrors the segment naming convention.\n"
    ),
}


def create_structure(root: Path) -> None:
    """
    Create the folder hierarchy and drop a README.md into each
    top-level directory.

    Args:
        root: Root Path where the dataset will live.
    """
    root.mkdir(parents=True, exist_ok=True)
    created: list[str] = []

    for rel_path, _ in STRUCTURE:
        folder = root / rel_path
        folder.mkdir(parents=True, exist_ok=True)
        created.append(str(folder))

        # Write a README only for top-level dirs (no slash in rel_path prefix)
        top_level = rel_path.split("/")[0]
        readme_path = root / top_level / "README.md"
        if top_level in README_CONTENTS and not readme_path.exists():
            readme_path.write_text(README_CONTENTS[top_level])

    # Also write a top-level .gitignore to keep previews & final data out of git
    gitignore = root / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(
            "# Auto-generated previews\npreviews/\n\n"
            "# Final processed datasets (large binaries)\nfinal_dataset/\n"
        )

    return created


def print_tree(root: Path) -> None:
    """
    Print a pretty ASCII tree of the created structure.

    Args:
        root: Root Path of the dataset.
    """
    print(f"\n{BOLD}{CYAN}Dataset structure created at: {root}{RESET}\n")
    print(f"{BOLD}{root.name}/{RESET}")

    entries = [(rel, desc) for rel, desc in STRUCTURE]
    seen_top = set()

    for rel_path, desc in entries:
        parts  = rel_path.split("/")
        top    = parts[0]
        indent = "  " * (len(parts) - 1)
        prefix = "├── " if parts[-1] != STRUCTURE[-1][0].split("/")[-1] else "└── "

        if top not in seen_top:
            # Print top-level dir with description annotation
            seen_top.add(top)
            print(f"  {CYAN}├── {top}/{RESET}  {DIM}# {desc}{RESET}"
                  if top != "final_dataset" else
                  f"  {CYAN}├── {top}/{RESET}  {DIM}# {desc}{RESET}")
        else:
            # Print sub-dirs indented under their parent
            print(f"    {DIM}│   └── {parts[-1]}/{RESET}  {DIM}# {desc}{RESET}")

    print(f"\n{GREEN}✔ Folder structure ready.{RESET}")
    print(f"{DIM}A README.md and .gitignore have been placed in the root.{RESET}\n")


# ─── MAIN ──────────────────────────────────────────────────
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python setup_structure.py <dataset_root>")
        sys.exit(1)

    root = Path(sys.argv[1])
    create_structure(root)
    print_tree(root)
